/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddLeadModalComponent: typeof import('./src/components/AddLeadModalComponent.vue')['default']
    AsideComponent: typeof import('./src/components/AsideComponent.vue')['default']
    BarChartIconButton: typeof import('./src/components/buttons/BarChartIconButton.vue')['default']
    BaseButton: typeof import('./src/components/buttons/BaseButton.vue')['default']
    BaseButtonLink: typeof import('./src/components/buttons/BaseButtonLink.vue')['default']
    CardComponent: typeof import('./src/components/CardComponent.vue')['default']
    ChartContainerComponent: typeof import('./src/components/ChartContainerComponent.vue')['default']
    ContactPageIconButton: typeof import('./src/components/buttons/ContactPageIconButton.vue')['default']
    copy: typeof import('./src/components/LineChartContainerComponent copy.vue')['default']
    DeckComponent: typeof import('./src/components/DeckComponent.vue')['default']
    DoughnutChartContainerComponent: typeof import('./src/components/DoughnutChartContainerComponent.vue')['default']
    DummyComponent: typeof import('./src/components/DummyComponent.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HouseIcon: typeof import('./src/components/buttons/HouseIcon.vue')['default']
    HouseIconButton: typeof import('./src/components/buttons/HouseIconButton.vue')['default']
    IconComponent: typeof import('./src/components/IconComponent.vue')['default']
    LayersIconButton: typeof import('./src/components/buttons/LayersIconButton.vue')['default']
    LineChartContainerComponent: typeof import('./src/components/LineChartContainerComponent.vue')['default']
    NotificationsIconButton: typeof import('./src/components/buttons/NotificationsIconButton.vue')['default']
    ScreenShareIconButton: typeof import('./src/components/buttons/ScreenShareIconButton.vue')['default']
    ShareScreenIconButton: typeof import('./src/components/buttons/ShareScreenIconButton.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    TableComponent: typeof import('./src/components/TableComponent.vue')['default']
    TableContainerComponent: typeof import('./src/components/TableContainerComponent.vue')['default']
    UserBadgeComponent: typeof import('./src/components/UserBadgeComponent.vue')['default']
    UserIconButton: typeof import('./src/components/buttons/UserIconButton.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
